### ISSUE TITLE
[resolved]There will be misalignment when used simultaneously with Beautify-Anki.

### ISSUE THREAD

**Issue by fatsheep2** [shigeyukey/Anki-Terminator-#18] opened 2024-08-22 11:31 UTC
When I use Beautify-Anki and Anki-Terminator together, the Anki-Terminator window floats in the top left corner, which is a bug. However, when I close Beautify-Anki and restart, everything returns to normal. I am writing this to share my experience with others. They can work together with Beautify-Anki and work well!

first ,close your beautify-anki
 like:

![图片](https://github.com/user-attachments/assets/c633c24e-b98d-4c92-a32f-b9eefb888db0)

then,open your beautify-anki

then like:

![图片](https://github.com/user-attachments/assets/54fa0acd-b285-49ab-8668-42dbab2c428d)

(As long as this plugin is opened before Beautify-Anki, it will work fine)

OS:ArchCraft(Linux)
DE: hyprland(wayland)

**Comment by shigeyukey** [comment] 2024-08-26 13:21
Hello, thank you for reporting the problem and the solution.
I tried to reproduce the problem on Windows, but I can't seem to reproduce it, so it may be a Linux-only bug. (Another user has reported this problem before.)
Ideally I would like to prevent this problem, so I will try to see if I can reproduce the problem next time I debug on Linux.

**Comment by fatsheep2** [comment] 2024-08-27 04:46
> Hello, thank you for reporting the problem and the solution.
I tried to reproduce the problem on Windows, but I can't seem to reproduce it, so it may be a Linux-only bug. (Another user has reported this problem before.)
Ideally I would like to prevent this problem, so I will try to see if I can reproduce the problem next time I debug on Linux.

![微信图片_20240827123829](https://github.com/user-attachments/assets/14471454-1411-4206-8acf-1b5b134ba519)
win11 also has the same problem, I found the problem seems to be in awesome TTS(plugin code 1436550454), when I tried to disable, the problem solved,Linux and Win are the same, but I am not sure why, if there is anything I need to do, let me know

どうやらawesome TTS(プラグインコード1436550454)に問題があるようです。無効にしようとしたところ問題は解決しました。LinuxもWinも同じですが、理由が分かりません。

My plugin List:

![图片](https://github.com/user-attachments/assets/85495072-ea00-4137-b522-91211d435bcb)

**Comment by skyfox6688** [comment] 2024-09-07 02:33
> When I use Beautify-Anki and Anki-Terminator together, the Anki-Terminator window floats in the top left corner, which is a bug. However, when I close Beautify-Anki and restart, everything returns to normal. I am writing this to share my experience with others. They can work together with Beautify-Anki and work well!
> 
> first ,close your beautify-anki like:
> 
> ![图片](https://private-user-images.githubusercontent.com/41755477/360411391-c633c24e-b98d-4c92-a32f-b9eefb888db0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2NzY2NzEsIm5iZiI6MTcyNTY3NjM3MSwicGF0aCI6Ii80MTc1NTQ3Ny8zNjA0MTEzOTEtYzYzM2MyNGUtYjk4ZC00YzkyLWEzMmYtYjllZWZiODg4ZGIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA3VDAyMzI1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkNjVmZGJiOGZhMDE5MTgwNWM1YTQwYzEzYmE1NWY5ZTQzNDkxMGY4OTgyYzQwYjZkYzYzYmQzY2JiMWEyMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8EOe5HpA9KnYDofaTmO30H2pboxCjYBYJXupk6KFH58)
> 
> then,open your beautify-anki
> 
> then like:
> 
> ![图片](https://private-user-images.githubusercontent.com/41755477/360411763-54fa0acd-b285-49ab-8668-42dbab2c428d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2NzY2NzEsIm5iZiI6MTcyNTY3NjM3MSwicGF0aCI6Ii80MTc1NTQ3Ny8zNjA0MTE3NjMtNTRmYTBhY2QtYjI4NS00OWFiLTg2NjgtNDJkYmFiMmM0MjhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA3VDAyMzI1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjY2ZlODAwN2YwNDA5NjBkNDE5ODllMjNmNTA5MGM3ZDUyMGY1ZmE2MWVkNTgxZDA1MmVmNWVlMTA4NGZhMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OZHGbu5_SOC3nSAWUdrcYr1mAr3mFAD-M78TTcFRGYA)
> 
> (As long as this plugin is opened before Beautify-Anki, it will work fine)
> 
> OS:ArchCraft(Linux) DE: hyprland(wayland)

![image](https://github.com/user-attachments/assets/a5255ade-0d4b-4d13-8fcb-c6c9af5147ef)
这个怎么实现的，安装了那个插件
![image](https://github.com/user-attachments/assets/49e18883-76c0-4d6d-8d58-113c514093e2)

**Comment by fatsheep2** [comment] 2024-09-07 03:54
> > When I use Beautify-Anki and Anki-Terminator together, the Anki-Terminator window floats in the top left corner, which is a bug. However, when I close Beautify-Anki and restart, everything returns to normal. I am writing this to share my experience with others. They can work together with Beautify-Anki and work well!
> > first ,close your beautify-anki like:
> > ![图片](https://private-user-images.githubusercontent.com/41755477/360411391-c633c24e-b98d-4c92-a32f-b9eefb888db0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2NzY2NzEsIm5iZiI6MTcyNTY3NjM3MSwicGF0aCI6Ii80MTc1NTQ3Ny8zNjA0MTEzOTEtYzYzM2MyNGUtYjk4ZC00YzkyLWEzMmYtYjllZWZiODg4ZGIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA3VDAyMzI1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkNjVmZGJiOGZhMDE5MTgwNWM1YTQwYzEzYmE1NWY5ZTQzNDkxMGY4OTgyYzQwYjZkYzYzYmQzY2JiMWEyMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8EOe5HpA9KnYDofaTmO30H2pboxCjYBYJXupk6KFH58)
> > then,open your beautify-anki
> > then like:
> > ![图片](https://private-user-images.githubusercontent.com/41755477/360411763-54fa0acd-b285-49ab-8668-42dbab2c428d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2NzY2NzEsIm5iZiI6MTcyNTY3NjM3MSwicGF0aCI6Ii80MTc1NTQ3Ny8zNjA0MTE3NjMtNTRmYTBhY2QtYjI4NS00OWFiLTg2NjgtNDJkYmFiMmM0MjhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA3VDAyMzI1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjY2ZlODAwN2YwNDA5NjBkNDE5ODllMjNmNTA5MGM3ZDUyMGY1ZmE2MWVkNTgxZDA1MmVmNWVlMTA4NGZhMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OZHGbu5_SOC3nSAWUdrcYr1mAr3mFAD-M78TTcFRGYA)
> > (As long as this plugin is opened before Beautify-Anki, it will work fine)
> > OS:ArchCraft(Linux) DE: hyprland(wayland)
> 
> ![image](https://private-user-images.githubusercontent.com/68485812/365334990-a5255ade-0d4b-4d13-8fcb-c6c9af5147ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2ODE0ODMsIm5iZiI6MTcyNTY4MTE4MywicGF0aCI6Ii82ODQ4NTgxMi8zNjUzMzQ5OTAtYTUyNTVhZGUtMGQ0Yi00ZDEzLThmY2ItYzZjOWFmNTE0N2VmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA3VDAzNTMwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyYTgzNzM3NTEzMmZkNjgwNDZhMjM2MmUzOWQwNDRiODg5ZjBlMzM4M2ZkNWNjMTk5OTAwMjI1ZDgwZDNlMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gASURRJBcC3bGc0YkUfT_haMwS2mJl6OGvn_IK7ETYE) 这个怎么实现的，安装了那个插件 ![image](https://private-user-images.githubusercontent.com/68485812/365335010-49e18883-76c0-4d6d-8d58-113c514093e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2ODE0ODMsIm5iZiI6MTcyNTY4MTE4MywicGF0aCI6Ii82ODQ4NTgxMi8zNjUzMzUwMTAtNDllMTg4ODMtNzZjMC00ZDZkLThkNTgtMTEzYzUxNDA5M2UyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA3VDAzNTMwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwYWQ1YzFmY2MwMTM4YzFlZDI4MDYxNzk5MGI1NzkxYjQwZWUxNWFiMmI0OTNjMzViZTU3YzcyMDhhODdmY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zTnD58i72CNnhR4FRWPCzxGJawiz7UWpPczrXoID_wE)

这个和上面那个热力图是一起的，你下载的是 学习和复习卡片时候的进度条，热力图插件叫review heatmap

**Comment by fatsheep2** [comment] 2024-09-07 04:08
@shigeyukey お早う、宜しく

I found that the problem might be with other plug-ins, because when I open awesome TTS, the problem also occurs. I noticed that it has been updated in the past two days. I will continue testing after the update. Thank you for your efforts!

**Comment by shigeyukey** [comment] 2024-09-16 18:22
This add-on can no longer be updated due to a bug, so I changed it to the new add-on page.
* new add-on code : 1468920185
* new addon page : [🤖Anki Terminator V2](https://ankiweb.net/shared/info/1468920185)

I tried to reproduce the problem but can't seem to do it. (It is showing up fine despite having all those add-ons.)
I added a workaround to V2, is the problem still occurring?

**Comment by shigeyukey** [comment] 2024-09-17 23:32
According to the rating comments on the add-on page, this problem seems to have been resolved in the update. If the problem reoccurs please contact me again.

**Closed as completed by shigeyukey** 2024-09-17 23:32 UTC
Labels: bug
